config/routes.rb
Rails.application.routes.draw do
  resources :documents, only: [:new, :create, :show]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  devise_for :users
  resources :projects do
    resources :assets, only: [:create]
    resources :tasks do
      resources :comments, only: [:create]
      member do
        patch :toggle
      end
    end
  end


  root 'projects#index'
end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :project
  has_many :comments
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy, :toggle]

  # GET /tasks
  # GET /tasks.json
  def index
    @tasks = Task.all
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @project = Project.find params[:project_id]
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
    @project = Project.find params[:project_id]
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @project = Project.find params[:project_id]
    @task = @project.tasks.build(task_params)

    respond_to do |format|
      if @task.save
        format.html { redirect_to @project, notice: 'Task was successfully created.' }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to @task, notice: 'Task was successfully updated.' }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url, notice: 'Task was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def toggle
    @task.toggle(:done).save
    DefaultMailer.confirm_task(@task).deliver_later if @task.comments.any?
    head 204 # No Content
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.require(:task).permit(:title, :done)
    end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_form.html.erb
<%= form_for([@project, @task]) do |f| %>
  <% if @task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>
      <ul>
      <% @task.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title, class: "form-control" %>
  </p>

  <p>
    <%= f.check_box :done %>
    <%= f.label :done %>
  </p>

  <p>
    <%= f.submit class: "btn btn-primary" %>
  </p>
<% end %>

app/views/tasks/edit.html.erb
<h1>Editing Task</h1>

<%= render 'form' %>

<%= link_to 'Show', @task %> |
<%= link_to 'Back', tasks_path %>

app/views/tasks/index.html.erb
<h1>Listing Tasks</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Done</th>
      <th>Project</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tasks.each do |task| %>
      <tr>
        <td><%= task.title %></td>
        <td><%= task.done %></td>
        <td><%= task.project %></td>
        <td><%= link_to 'Show', task %></td>
        <td><%= link_to 'Edit', edit_task_path(task) %></td>
        <td><%= link_to 'Destroy', task, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Task', new_task_path %>

app/views/tasks/new.html.erb
<h1>New Task</h1>

<%= render 'form' %>

<%= link_to 'Back', @project %>

app/views/tasks/show.html.erb
<h1>
  <%= check_box_tag :task_done, "", @task.done %>
  <%= @task.title %>
</h1>

<p>
  <strong>Project:</strong>
  <%= link_to @task.project.name, @task.project %>
</p>

<%= link_to 'Edit', edit_project_task_path(@task.project, @task) %> |
<%= link_to 'Back', @task.project %>

<h2>Comments</h2>

<ol>
  <% @task.comments.each do |comment| %>
  <li>
    <h3><%= comment.name %> <small><%= comment.email %></small> </h3>
    <blockquote><%= comment.body %></blockquote>
  </li>
  <% end %>
</ol>

<%= form_for([ @task.project, @task, @task.comments.build ]) do |f| %>
<p>
  <%= f.text_field :name, placeholder: "Name", class: "form-control" %>
</p>

<p>
  <%= f.email_field :email, placeholder: "Email", class: "form-control" %>
</p>

<p>
  <%= f.text_area :body, rows: 8, cols: 50, class: "form-control" %>
</p>

<p>
  <%= f.submit class: "btn btn-primary" %>
</p>
<% end %>