config/routes.rb
Rails.application.routes.draw do
  resources :documents, only: [:new, :create, :show]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  devise_for :users
  resources :projects do
    resources :assets, only: [:create]
    resources :tasks do
      resources :comments, only: [:create]
      member do
        patch :toggle
      end
    end
  end


  root 'projects#index'
end

app/models/project.rb
class Project < ActiveRecord::Base
  has_many :tasks
  has_many :assets

  validates :name, presence: true

  acts_as_paranoid

  # searchable do
  #   text :name, :description
  # end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  layout "projects"

  # GET /projects
  # GET /projects.json
  def index
    @projects = if params[:q]
      Project.search { keywords params[:q] }.results
    else
      Project.page(params[:page] || 1).per(params[:per_page] || 5).all
    end
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    render layout: "application"
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
    authorize @project
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:name, :ends_at, :description)
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_assets.html.erb
<h3>Assets for the project</h3>

<ul>
  <%- @project.assets.each do |asset| %>
    <li>
      <%= link_to asset.file_url do %>
        <%= image_tag asset.file_url(:thumb), width: 120 if asset.file_url =~ /(gif|jpg|jpeg|png|bmp)$/ %>
        <%= asset.file_identifier %>
      <%- end %>
    </li>
  <% end %>
</ul>

<%= form_for [ @project, @project.assets.build ], multipart: true do |f| %>
<p>
  <%= f.file_field :file %>
  <%= f.submit %>
</p>
<% end %>

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :name, t("projects.name") %><br>
    <%= f.text_field :name, class: "form-control" %>
  </p>

  <p>
    <%= f.label :description, t("projects.description") %><br>
    <%= f.text_area :description, class: "form-control" %>
  </p>

  <p>
    <%= f.label :ends_at, t("projects.ends_at") %><br>
    <%= f.date_select :ends_at %>
  </p>

  <p>
    <%= f.submit class: "btn btn-primary" %>
  </p>
<% end %>

app/views/projects/edit.html.erb
<h1>Editing Project</h1>

<%= render 'form' %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<h1>Projects</h1>

<%= form_tag projects_path, method: :get do %>
<p>
  <%= text_field_tag :q, "", placeholder: "Search projects" %>
  <%= button_tag "Search" %>
</p>
<% end %>

<div class="row">
    <nav id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block bg-light sidebar collapse">
      <div class="sidebar-sticky pt-3">
        <% content_for(:sidebar) do %>
          <h3>All projects</h3>
          <ol class="list-group">
            <% Project.all.each do |project| %>
            <li class="list-group-item"><%= link_to project.name, project %></li>
            <% end %>
          </ol>
        <% end %>
      </div>
    </nav>
  </div>

  <div class="row">
    <table class="table table-hover">
        <thead>
          <tr>
            <th>Name</th>
            <th>Ends at</th>
            <th></th>
          </tr>
        </thead>

        <tbody>
          <% @projects.each do |project| %>
            <tr>
              <td>
                <%= link_to project.name, project %>
              </td>
              <td><%= l project.ends_at, format: :long %></td>
              <td>
                <%= link_to 'Edit', edit_project_path(project) %>
                &bull;
                <%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } %>

              </td>
            </tr>
          <% end %>
        </tbody>
      </table>

      <%= paginate @projects, theme: "twitter-bootstrap-3" %>
  </div>





<p>
  <%= link_to 'New Project', new_project_path, class: "btn btn-primary" %>
</p>

  
</div>

app/views/projects/new.html.erb
<h1>New Project</h1>

<%= render 'form' %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<h1>
  <%= @project.name %>
</h1>

<blockquote><%= @project.description %></blockquote>

<p>
  <strong>Ends at:</strong>
  <%= @project.ends_at %>
</p>

<h2>Tasks for this project</h2>

<ul>
  <% @project.tasks.each do |task| %>
  <li>
    <%= check_box_tag "task_done_#{task.id}", "", task.done, class: "task_done", data: { id: task.id, toggle_path: toggle_project_task_path(@project, task) } %>
    <%= link_to task.title, [@project, task] %>
  </li>
  <% end %>
</ul>

<p>
  <%= link_to "New task", new_project_task_path(@project), class: "btn btn-primary" %>
</p>

<%= render "assets" %>

<%= link_to 'Edit', edit_project_path(@project) %> |
<%= link_to 'Back', projects_path %>